### ISSUE TITLE
Usability testing

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#222]
What's the plan for it? (Public facing)

- [x] Complete test plan https://docs.google.com/document/d/1NY4HnTeFn1UYHNRrVk-rdwoUxWMkGMvAEM-Kl4jZZAI/edit
- [x] Schedule test
- [x] Conduct tests
- [x] Analyze results from test and file specific issues to fix
- [x] Get Gift cards to incentivize participants

**Comment by luqmaan** [comment]
We conducted and analyzed tests yesterday.

- Test plan: https://docs.google.com/document/d/1NY4HnTeFn1UYHNRrVk-rdwoUxWMkGMvAEM-Kl4jZZAI/edit
- Note taking form: https://airtable.com/shrMkympxPTmNCsWu
- Raw notes from testing: https://airtable.com/appvBAMDZHxDxsUda
- Synthesis whiteboard picture:  
![image](https://user-images.githubusercontent.com/1275831/39317679-cd4237da-4941-11e8-9218-261cf262f62c.png)

Based on our testing and synthesis, here's what we decided are the top things to improve:

- The search bar doesn't work
  - There is no obvious primary action
  - Can't use enter/go on Desktop
  - The search bar doesn't look active on mobile when clicked
  - Searching for addresses did not work
  - The quality of the geocoder is important
    - We can't use the Google geocoder/places API with Mapbox
  - Users don't understand what the suggested search items are
- Mobile user are confused when they click on a marker. Where did the map go?
- The back button on Android doesn't work on many pages, e.g. marker detail
- The map is sluggish on mobile devices
- Users interpreted the map markers differently
  - Examples:
    - Markers are related to weather radar colors
    - Markers indicate danger or safety of a place. E.g. yellow means you need to leave this area, green mean its a safe place to go to. 
  - This was more clear to desktop users
- The timestamps in the history section are confusing
- Users had lots of questions around the open data tab. Its purpose was unclear.
- Pinching on mobile made the page zoom in, which made it difficult to zoom into the map
- Users are not aware of the extend of flooding based on markers. How flooded is a closed marker vs a caution marker?
- Its not clear how users how the data is created and how much they can trust the data.

Other things we learned:

- The users we tested with all wanted navigation/GPS/routing
- None of the users we tested with clicked on the communities dropdown


The next time we test we should:

- Use real data. Use a snapshot of ATXfloods data from a storm as oppose to randomly updating crossings.
- Start by showing users only closed crossings instead of only open crossings. Are users less confused by this?

We'd like to work on these improvements, ordered by priority:

1. Search bar not working
2. Confused when clicking on a marker in mobile and the map disappearing
3. The map is sluggish
  - Show only caution/closed markers by default
  - Consider clustering
4. Varying meanings of dots
5. Back button doesn't work on Android
6. Zooming on mobile
