### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#370]
Problem: When I created a new user and attempted to reset my password from the email link sent, I recieved an error message "Server Error. Failed to reset password."

Tested on Windows 10 with Chrome v70 and Apple OSX Chrome v69

Steps to recreate:
1. Log in as an admin
2. Create a user
3. click on the link to reset password sent to email address associated with new user
4. set password and re-enter the same password. I tried:
* abc123!@#
* password
* passw0rd

Expected results:
Passwords match and should be accepted into the system

Actual results:
Receive error message.
![screen shot 2018-10-29 at 12 41 05 pm](https://user-images.githubusercontent.com/1779067/47669137-34037380-db78-11e8-921b-b2d8a9c8fa4a.png)

**Comment by Niicck** [comment]
I believe this bug happens when you're still logged in as an admin, but then trying to reset someone else's password. Quick workaround for now would be to log out of the admin account before reseting the password. I'll work on automatically logging someone off the admin account if they hit the password reset page.

**Comment by Niicck** [comment]
I am not able to recreate this. Your test might have happened during a deployment when some pieces were in transition. Let's meet up and see if we can't replicate it.

**Comment by wilhitem** [comment]
verified!
