### ISSUE TITLE
Experiment with Prisma

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/ctxfloods#426]
Test it out. See if it works better than postgraphile.

**Comment by benjie** [comment]
What issues are you having with PostGraphile, and how can I help?

**Comment by Niicck** [comment]
Hi @benjie! I appreciate you responding. We recently migrated from postgraphql to postgraphile. Right away we experienced some noticeable latency issues. A simple graphql request now takes about 800ms.

I think our trouble stems from using postgraphile on a serverless backend, which I know is not the intended use case for this library. I'd prefer not to rearchitect our infrastructure, change our deployment process, and implement elastic beanstalk just to use EC2 for a single endpoint. Since there are many examples of people using prisma serverlessly with success, we decided it would be worth looking into.

One of the significant changes for us when migrating from postgraphql was the fact that we are now forced to use Pools instead of Clients when connecting to postgres. Other than that, I'm not sure what else could've changed to cause such a big performance dip. I tried a couple of things to see if I could reduce our latency. Previously, we built and destroyed a connection pool on each lambda invocation.  So I tired adding a persistent db pool of size 1 outside of the handler function. Somehow, this made our response time slightly worse (into the 800-900ms range)(https://github.com/cityofaustin/ctxfloods-backend/blob/425-scale/handlers/graphqlHandler.js). I then tried moving our lambda into the same VPC as our database. Depending on whether the lambda instance is warm or not (I'm assuming), we're seeing times from the 600ms-1s.

I'd prefer to keep using postgraphile, but our serverless project might not be the best fit for it.

**Comment by benjie** [comment]
Requests are slow because you're building the entire GraphQL schema again and again for every single request. Even with the cache (which avoids repeated introspection) that's a lot of work - PostGraphile does a lot at schema _build_ time to make schema _execution_ fast.

Try moving the schema build outside the request handler:

```js
const floodsPool = require('../db/helpers/getClient')({
  clientType: 'floodsAPI',
  pool: true
});

/* 👇 Build schema OUTSIDE of the request handler */
const schemaPromise = createPostGraphileSchema(floodsPool, "floods", {
    jwtSecret: process.env.JWT_SECRET,
    jwtPgTypeIdentifier: 'floods.jwt_token',
    pgDefaultRole: 'floods_anonymous',
    disableDefaultMutations: true,
    readCache: `${__dirname}/../pgCatalog/postgraphile.cache`
  })
/* ☝️ */

module.exports.handle = (event, context, cb) => {
  context.callbackWaitsForEmptyEventLoop = false; // Allows you to persist floodsPool after lambda invocation
  let schema;

  return schemaPromise.then((schema) => {
    const jwtToken = extractToken(event);
    return withPostGraphileContext(
      {
        pgPool: floodsPool,
        jwtToken: jwtToken,
        jwtSecret: process.env.JWT_SECRET,
        pgDefaultRole: 'floods_anonymous'
      }, (graphileContext) => {
        return graphql(
          schema,
          event.query,
          null,
          graphileContext,
          event.variables,
          event.operationName
        )
      })
  })
  .then((response)=> {
    response.statusCode = 200;
    response.headers = { 'Access-Control-Allow-Origin': '*' };
    cb(null, response);
  })
  .catch((err)=>{
    logError(err);
    let response = {};
    response.statusCode = 500;
    response.headers = { 'Access-Control-Allow-Origin': '*' };
    response.errors = [err];
    cb(null, response)
  })
}
```

---

This aside, we did some massive improvements to Lambda support in 4.1.0. To leverage them you're going to want to compile your PostGraphile instance (e.g. using webpack); here's an example you can use as a basis:

https://github.com/graphile/postgraphile-lambda-example

and here's the release notes:

https://github.com/graphile/postgraphile/releases/tag/v4.1.0

If you do the above, then you no longer need to do your own `withPostGraphileContext` / `createPostGraphileSchema` / etc dance; you can just use the `postgraphile` middleware directly and still reap great performance in Lambda.

I should probably start building a prebuilt postgraphile.js you can just upload to Lambda!

---

Let me know how you get on with this change; hopefully it'll make a world of difference to you! Don't hesitate to reach out in future, our discord is a great place to sanity check issues like this: http://discord.gg/graphile

You should find that PostGraphile has significantly better performance than PostGraphQL did.

**Comment by Niicck** [comment]
This is great news! I didn't know about the developments in v4.1. I'll get our code running with those optimizations and let you know how it goes. Thanks for the reply - this is going to save us a ton of pain.

**Comment by benjie** [comment]
No probs; do give me a shout on discord if you have any issues 👍
